---
title: "OromiaDataSet"
author: "Berea Etherton"
date: "10/21/2021"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(igraph)
library(readxl)
library(viridis)
```

```{r fig.width=12, fig.height=12, dpi=100}

StakeHolder <- read_excel("StakeHolder.xlsx")
dim(StakeHolder)
StakeHolder<-StakeHolder[,2:12]
rownames(StakeHolder)<-c("Research Centers","Policy Makers","QDS Producers",
                         "Private Seed Co.","Ware potato farmers","Input dealers","Potato traders",
                         "NGOS","Seed regulators","Coop. Union","Extension Support")
colnames(StakeHolder)<-c("Research Centers","Policy Makers","QDS Producers",
                         "Private Seed Co.","Ware potato farmers","Input dealers","Potato traders",
                         "NGOS","Seed regulators","Coop. Union","Extension Support")
#View(StakeHolder)
StakeHolder<-as.matrix(StakeHolder)
StakeHolder<-round(StakeHolder)
diag(StakeHolder)<-0
head(StakeHolder)

print("Where a value of 5 represents very strong interactions and communications, implement joint R&D activities and 1 represents no interactions or formal communications")


net<-graph_from_adjacency_matrix(StakeHolder,weighted=TRUE,mode="directed")
l<-matrix(c(1.2,4.4,#research
            1,3, #policy
            3.2,4, #QDS
            2.7,4.8, #private
            2.15,3, #ware
            2.6,1.1, #input
            3.1,1.8, #pot trade
            1.2,1.8, #NGO
            2,5, #seed reg
            1.9,1, #coop union
            3.3,2.8), #extension sup
          nrow=11,ncol=2,byrow = TRUE)
nd<-graph.strength(net)
pal1<-viridis_pal(option = "magma")(11)
colrs<-setNames(c(pal1[c(1,10,7,5,3)]),c(unique(E(net)$weight)))
E(net)$color<-colrs[E(net)$weight]

plot(net,vertex.label.color="black",vertex.frame.color=NA,vertex.color=pal1[9],edge.curved=0.4,
     edge.width=ifelse(E(net)$weight<2,0,(E(net)$weight*log(E(net)$weight))),edge.arrow.size=1.1,
     edge.color=ifelse(E(net)$weight<2,"NA",E(net)$color),vertex.size=nd*log(nd*0.3)*0.3,layout=l,
     vertex.lebel.cex=10,vertex.label.family="sans")
legend("bottomleft",c("2","3","4","5"),pch=15,
       bty="n",col=colrs[2:5],pt.cex=2,
       title="Edge Weight")


plot(net,vertex.label.color="black",vertex.frame.color=NA,vertex.color=pal1[9],edge.curved=0.4,
     edge.width=ifelse(E(net)$weight<5,0,(E(net)$weight*log(E(net)$weight))),edge.arrow.size=1.2,
     edge.color=ifelse(E(net)$weight<5,"NA",E(net)$color),vertex.size=nd*log(nd*0.3)*0.3,layout=l,
     vertex.lebel.cex=10,vertex.label.family="sans")
legend("bottomleft",c("5"),pch=15,
       bty="n",col=colrs[5],pt.cex=2,
       title="Edge Weight")


plot(net,vertex.label.color="black",vertex.frame.color=NA,vertex.color=pal1[9],edge.curved=0.4,
     edge.width=ifelse(E(net)$weight<4,0,(E(net)$weight*log(E(net)$weight))),edge.arrow.size=1.2,
     edge.color=ifelse(E(net)$weight<4,"NA",E(net)$color),vertex.size=nd*log(nd*0.3)*0.3,layout=l,
     vertex.lebel.cex=10,vertex.label.family="sans")
legend("bottomleft",c("4","5"),pch=15,
       bty="n",col=colrs[4:5],pt.cex=2,
       title="Edge Weight")

plot(net,vertex.label.color="black",vertex.frame.color=NA,vertex.color=pal1[9],edge.curved=0.4,
     edge.width=ifelse(E(net)$weight<3,0,(E(net)$weight*log(E(net)$weight))),edge.arrow.size=1.2,
     edge.color=ifelse(E(net)$weight<3,"NA",E(net)$color),vertex.size=nd*log(nd*0.3)*0.3,layout=l,
     vertex.lebel.cex=10,vertex.label.family="sans")
legend("bottomleft",c("3","4","5"),pch=15,
       bty="n",col=colrs[3:5],pt.cex=2,
       title="Edge Weight")

plot(net,vertex.label.color="black",vertex.frame.color=NA,vertex.color=pal1[9],edge.curved=0.4,
     edge.width=ifelse(E(net)$weight<2,0,(E(net)$weight*log(E(net)$weight))),edge.arrow.size=1.2,
     edge.color=ifelse(E(net)$weight<2,"NA",E(net)$color),vertex.size=nd*log(nd*0.3)*0.3,layout=l,
     vertex.lebel.cex=10,vertex.label.family="sans")
legend("bottomleft",c("2","3","4","5"),pch=15,
       bty="n",col=colrs[2:5],pt.cex=2,
       title="Edge Weight")

graph.strength(net)

```